steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - meetwater-backend
      - --source=.
      - --region=europe-west9
      - --allow-unauthenticated
      - --port=8080
      - --set-env-vars=ALLOWED_ORIGINS=https://meetwater.fr,https://www.meetwater.fr
      - --set-secrets=DATABASE_HOSTNAME=DATABASE_HOSTNAME:latest,DATABASE_PORT=DATABASE_PORT:latest,DATABASE_NAME=DATABASE_NAME:latest,DATABASE_USERNAME=DATABASE_USERNAME:latest,DATABASE_PASSWORD=DATABASE_PASSWORD:latest,SECRET_KEY=SECRET_KEY:latest,ALGORYTHM=ALGORYTHM:latest,ACCESS_TOKEN_EXPIRE_MINUTES=ACCESS_TOKEN_EXPIRE_MINUTES:latest,FROM_EMAIL=FROM_EMAIL:latest,SMTP_HOST=SMTP_HOST:latest,SMTP_PORT=SMTP_PORT:latest,SMTP_USER=SMTP_USER:latest,SMTP_PASSWORD=SMTP_PASSWORD:latest,FRONTEND_BASE_URL=FRONTEND_BASE_URL:latest
      - --project=$PROJECT_ID

options:
  logging: CLOUD_LOGGING_ONLY
