"""add_swimmer_booking_link

Revision ID: 089534961857
Revises: 4ad250213faf
Create Date: 2025-11-18 14:06:26.833614

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "089534961857"
down_revision: Union[str, Sequence[str], None] = "4ad250213faf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swimmers_bookings_link",
        sa.Column("swimmer_id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["swimmer_id"],
            ["swimmers.id"],
        ),
        sa.PrimaryKeyConstraint("swimmer_id", "booking_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("swimmers_bookings_link")
    # ### end Alembic commands ###
