"""add_swimming_pool_table_and_relation_to_coaches_and_managers

Revision ID: ac85314c8d92
Revises: 2ba6ed7122f0
Create Date: 2025-12-12 15:37:00.219910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac85314c8d92"
down_revision: Union[str, Sequence[str], None] = "2ba6ed7122f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swimming_pool",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pool_name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), unique=True, nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("post_code", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "pool_manager", sa.Column("swimming_pool_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        "fk_pool_manager_swimming_pool",
        "pool_manager",
        "swimming_pool",
        ["swimming_pool_id"],
        ["id"],
    )
    op.add_column(
        "swimming_coaches", sa.Column("swimming_pool_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        "fk_swimming_coaches_swimming_pool",
        "swimming_coaches",
        "swimming_pool",
        ["swimming_pool_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_swimming_coaches_swimming_pool", "swimming_coaches", type_="foreignkey"
    )
    op.drop_column("swimming_coaches", "swimming_pool_id")
    op.drop_constraint(
        "fk_pool_manager_swimming_pool", "pool_manager", type_="foreignkey"
    )
    op.drop_column("pool_manager", "swimming_pool_id")
    op.drop_table("swimming_pool")
    # ### end Alembic commands ###
