"""add_swimmer_representative_table_for_associations

Revision ID: 8a017db6d1ab
Revises: 1990b7dd70fd
Create Date: 2025-11-25 12:35:37.219603

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a017db6d1ab"
down_revision: Union[str, Sequence[str], None] = "1990b7dd70fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swimmers_representatives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("representative_id", sa.UUID(), nullable=False),
        sa.Column("swimmer_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["representative_id"],
            ["representatives.id"],
        ),
        sa.ForeignKeyConstraint(
            ["swimmer_id"],
            ["swimmers.id"],
        ),
        sa.PrimaryKeyConstraint("representative_id", "swimmer_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("swimmers_representatives")
    # ### end Alembic commands ###
