"""add_swimmer_table

Revision ID: 1990b7dd70fd
Revises: a531afb95a37
Create Date: 2025-11-25 11:53:38.549127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1990b7dd70fd"
down_revision: Union[str, Sequence[str], None] = "a531afb95a37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swimmers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "AQUAPHOBIC",
                "BEGINNER",
                "INTERMEDIATE",
                "CONFIRMED",
                name="swimmerlevel",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "birth_date <= current_date - interval '4 years'",
            name="check_minimum_age_4",
        ),
        sa.UniqueConstraint(
            "first_name", "last_name", "birth_date", name="uq_name_birthdate"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("swimmers", "level")
    op.execute("DROP TYPE IF EXISTS swimmerlevel")
    op.drop_table("swimmers")
    # ### end Alembic commands ###
