"""add_swimmer_table

Revision ID: e45bcd070362
Revises: bf343bf0853d
Create Date: 2025-11-16 21:44:29.447968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e45bcd070362"
down_revision: Union[str, Sequence[str], None] = "bf343bf0853d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "swimmers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "AQUAPHOBIC",
                "BEGINNER",
                "INTERMEDIATE",
                "CONFIRMED",
                name="swimmerlevel",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "birth_date <= current_date - interval '4 years'",
            name="check_minimum_age_4",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("swimmers")
    op.execute("DROP TYPE swimmerlevel")
    # ### end Alembic commands ###
