"""add_user_table

Revision ID: c159863403ab
Revises: 
Create Date: 2025-11-12 18:05:06.594823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c159863403ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('level', sa.ARRAY(sa.Enum('AQUAPHOBIC', 'BEGINNER', 'INTERMEDIATE', 'CONFIRMED', name='userlevel')), nullable=False),
    sa.Column('representative', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(EXTRACT(YEAR FROM AGE(CURRENT_DATE, birth_date)) >= 18) OR representative IS NOT NULL', name='user_representative_if_minor_check'),
    sa.CheckConstraint('EXTRACT(YEAR FROM AGE(CURRENT_DATE, birth_date)) >= 5', name='user_minimum_age_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
