"""add_relation_between_swimming_coach_and_booking

Revision ID: 2fd853dfd51b
Revises: 33fb6f2f4fd7
Create Date: 2025-11-25 19:02:46.739342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fd853dfd51b"
down_revision: Union[str, Sequence[str], None] = "33fb6f2f4fd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("swimming_coach_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        "fk_bookings_swimming_coach",
        "bookings",
        "swimming_coaches",
        ["swimming_coach_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_bookings_swimming_coach", "bookings", type_="foreignkey")
    op.drop_column("bookings", "swimming_coach_id")
    # ### end Alembic commands ###
