"""add_swimmer_booking_table_for_association

Revision ID: ef0d0d8ebc05
Revises: 5fff714ec748
Create Date: 2025-11-25 14:34:28.746087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef0d0d8ebc05"
down_revision: Union[str, Sequence[str], None] = "5fff714ec748"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swimmers_bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("swimmer_id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["swimmer_id"],
            ["swimmers.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("swimmer_id", "booking_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("swimmers_bookings")
    # ### end Alembic commands ###
