"""add_swimmer_user_link_table

Revision ID: 603185131fda
Revises: e45bcd070362
Create Date: 2025-11-16 21:54:02.497206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "603185131fda"
down_revision: Union[str, Sequence[str], None] = "e45bcd070362"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swimmer_user_link",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("swimmer_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["swimmer_id"],
            ["swimmers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "swimmer_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("swimmer_user_link")
    # ### end Alembic commands ###
