"""add_booking_table

Revision ID: 4ad250213faf
Revises: 603185131fda
Create Date: 2025-11-18 13:51:38.259825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ad250213faf"
down_revision: Union[str, Sequence[str], None] = "603185131fda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("booked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_slot", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACCEPTED", "PASSED", "CANCELLED", name="booking_status_enum"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "booked_at > CURRENT_TIMESTAMP", name="ck_booking_booked_at_future"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bookings")
    op.execute("DROP TYPE booking_status_enum")
    # ### end Alembic commands ###
