"""add_swimming_coach_table

Revision ID: 33fb6f2f4fd7
Revises: ef0d0d8ebc05
Create Date: 2025-11-25 18:57:09.496353

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33fb6f2f4fd7"
down_revision: Union[str, Sequence[str], None] = "ef0d0d8ebc05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swimming_coach",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("last_caep_certification_date", sa.Date(), nullable=True),
        sa.Column("last_pse_certification_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "last_caep_certification_date IS NULL OR last_caep_certification_date >= current_date - interval '5 years'",
            name="check_last_caep_certification_date",
        ),
        sa.CheckConstraint(
            "last_pse_certification_date IS NULL OR last_pse_certification_date >= current_date - interval '1 year'",
            name="check_last_pse_certification_date",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("swimming_coach")
    # ### end Alembic commands ###
