"""add_CoachSchedule_table

Revision ID: 2ba6ed7122f0
Revises: be96e421c7da
Create Date: 2025-12-10 15:47:02.227554

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ba6ed7122f0"
down_revision: Union[str, Sequence[str], None] = "be96e421c7da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coaches_schedules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "activity",
            sa.Enum(
                "PUBLIC_LIFEGUARDING",
                "SCHOOL_LIFEGUARDING",
                "SCHOOL_SWIMMING_LESSONS",
                "AQUA_FITNESS",
                "AQUA_TRAINING",
                "AQUA_BOXING",
                "AQUA_BIKE",
                "GENTLE_AQUAFIT",
                "AQUA_HEALTH_TRAINING",
                "AQUATIC_PRESCHOOL_4_5",
                "AQUATIC_PRESCHOOL_5_6",
                "AVAILABLE",
                "ADULT_AQUAPHOBIC",
                "ADULT_BEGINNER",
                "ADULT_INTERMEDIATE",
                "ADULT_CONFIRMED",
                "CHILD_AQUAPHOBIC",
                "CHILD_BEGINNER",
                "CHILD_INTERMEDIATE",
                "CHILD_CONFIRMED",
                name="coach_activity",
            ),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("swimming_coach_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["swimming_coach_id"],
            ["swimming_coaches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coaches_schedules")
    op.execute("DROP TYPE IF EXISTS coach_activity")
    # ### end Alembic commands ###
