"""add_booking_table

Revision ID: 5fff714ec748
Revises: 8a017db6d1ab
Create Date: 2025-11-25 14:24:13.710671

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5fff714ec748"
down_revision: Union[str, Sequence[str], None] = "8a017db6d1ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("appointment_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACCEPTED", "PASSED", "CANCELLED", name="booking_status_enum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "appointment_at > CURRENT_TIMESTAMP", name="ck_booking_booked_at_future"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "status")
    op.execute("DROP TYPE IF EXISTS booking_status_enum")
    op.drop_table("bookings")
    # ### end Alembic commands ###
