"""add_swimming_coach_table_and_relations

Revision ID: e90912287e6f
Revises: 089534961857
Create Date: 2025-11-23 23:54:20.928216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e90912287e6f"
down_revision: Union[str, Sequence[str], None] = "089534961857"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swimming_coach",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("last_caep_certification_date", sa.Date(), nullable=True),
        sa.Column("last_pse_certification_date", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "last_caep_certification_date IS NULL OR last_caep_certification_date >= current_date - interval '5 years'",
            name="check_last_caep_certification_date",
        ),
        sa.CheckConstraint(
            "last_pse_certification_date IS NULL OR last_pse_certification_date >= current_date - interval '1 year'",
            name="check_last_pse_certification_date",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.add_column("bookings", sa.Column("swimming_coach_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        "fk_bookings_swimming_coach",
        "bookings",
        "swimming_coach",
        ["swimming_coach_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_bookings_swimming_coach", "bookings", type_="foreignkey")
    op.drop_column("bookings", "swimming_coach_id")
    op.drop_table("swimming_coach")
    # ### end Alembic commands ###
