"""add_swimmers_coaches_table

Revision ID: be96e421c7da
Revises: 3da3073f7330
Create Date: 2025-12-09 15:41:27.697095

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be96e421c7da"
down_revision: Union[str, Sequence[str], None] = "3da3073f7330"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swimmers_coaches",
        sa.Column("swimmer_id", sa.UUID(), nullable=False),
        sa.Column("swimming_coach_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["swimmer_id"],
            ["swimmers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["swimming_coach_id"],
            ["swimming_coaches.id"],
        ),
        sa.PrimaryKeyConstraint("swimmer_id", "swimming_coach_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("swimmers_coaches")
    # ### end Alembic commands ###
