"""add_user_pack_table

Revision ID: 893faf1bb97b
Revises: 9d84a8f2ade8
Create Date: 2026-02-05 23:16:10.707918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "893faf1bb97b"
down_revision: Union[str, Sequence[str], None] = "9d84a8f2ade8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_pack",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("representative_id", sa.UUID(), nullable=False),
        sa.Column("swimming_coach_id", sa.UUID(), nullable=False),
        sa.Column("sessions_total", sa.Integer(), nullable=False),
        sa.Column("sessions_remaining", sa.Integer(), nullable=False),
        sa.Column("price_paid", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID", "USED", "EXPIRED", name="pack_status_enum"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["representative_id"],
            ["representatives.id"],
        ),
        sa.ForeignKeyConstraint(
            ["swimming_coach_id"],
            ["swimming_coaches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_pack")
    op.execute("DROP TYPE IF EXISTS pack_status_enum")
    # ### end Alembic commands ###
