"""add_user_pack_table

Revision ID: ed1a401a96fa
Revises: 9d84a8f2ade8
Create Date: 2026-02-05 16:46:08.789828

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ed1a401a96fa"
down_revision: Union[str, Sequence[str], None] = "9d84a8f2ade8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
