"""add_coach_pack_table

Revision ID: c15165912346
Revises: 893faf1bb97b
Create Date: 2026-02-05 23:22:52.158476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c15165912346"
down_revision: Union[str, Sequence[str], None] = "893faf1bb97b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coach_pack",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("swimming_coach_id", sa.UUID(), nullable=False),
        sa.Column("sessions_count", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("final_price", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["swimming_coach_id"],
            ["swimming_coaches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coach_pack")
    # ### end Alembic commands ###
