"""add_relation_between_booking_and_userpack

Revision ID: 79ba87fc7bdf
Revises: c15165912346
Create Date: 2026-02-06 22:20:06.510088

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79ba87fc7bdf"
down_revision: Union[str, Sequence[str], None] = "c15165912346"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("user_pack_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_bookings_user_pack", "bookings", "user_pack", ["user_pack_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_bookings_user_pack", "bookings", type_="foreignkey", if_exists=True
    )
    op.drop_column("bookings", "user_pack_id")
    # ### end Alembic commands ###
