"""add_swimming_pool_schedule_table

Revision ID: fecf02aff343
Revises: ac85314c8d92
Create Date: 2026-01-02 23:50:44.665391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fecf02aff343"
down_revision: Union[str, Sequence[str], None] = "ac85314c8d92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swimming_pool_schedules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("swimming_pool_id", sa.UUID(), nullable=False),
        sa.Column(
            "day_of_week",
            sa.Enum(
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "SATURDAY",
                "SUNDAY",
                name="dayofweek",
            ),
            nullable=False,
        ),
        sa.Column("opening_time", sa.Time(), nullable=False),
        sa.Column("closing_time", sa.Time(), nullable=False),
        sa.CheckConstraint(
            "closing_time > opening_time", name="ck_opening_closing_times"
        ),
        sa.ForeignKeyConstraint(
            ["swimming_pool_id"], ["swimming_pools.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("idx_swimming_pool_slug"), table_name="swimming_pools")
    op.drop_index(op.f("ix_swimming_pools_slug"), table_name="swimming_pools")
    op.create_unique_constraint(None, "swimming_pools", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "swimming_pools", type_="unique")
    op.create_index(
        op.f("ix_swimming_pools_slug"), "swimming_pools", ["slug"], unique=True
    )
    op.create_index(
        op.f("idx_swimming_pool_slug"), "swimming_pools", ["slug"], unique=False
    )
    op.drop_table("swimming_pool_schedules")
    # ### end Alembic commands ###
